"""Сделал так, чтобы новая модель была видна

Revision ID: 35350e0e727b
Revises: e2d6c573b2ab
Create Date: 2026-05-16 14:00:55.644093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35350e0e727b'
down_revision: Union[str, Sequence[str], None] = 'e2d6c573b2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('current_user_id', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_machine')
    # ### end Alembic commands ###
