"""добавил таблицу для вирутальных машин

Revision ID: e2d6c573b2ab
Revises: 157d8d5b2c1f
Create Date: 2026-05-16 13:56:10.100340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d6c573b2ab'
down_revision: Union[str, Sequence[str], None] = '157d8d5b2c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
